version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: 
      context: './client'
    ports:
      - 3000:3000
#    volumes:
#      - test:/app
#      - /app/node_modules

  backend: 
    depends_on: 
      - db
    build: 
      context: './api'
    ports: 
      - 5000:5000
    # volumes:
    #   - test1:/app
    #   - /app/node_modules
    environment: 
      MONGO_URL: mongodb://db/mern
#    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - mern:/data/db

volumes:
  mern:
  test:
  test1:


# version: '3'
# services:
#   front:
#     build:
#       context: './client'
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     container_name: react-container
#     environment:
#       - WATCHPACK_POLLING=true
#     networks:
#       - mern-stack-network
#     volumes:
#       - ./client:/app
#     depends_on:
#       - backend
#   backend:
#     build:
#       context: './api'
#       dockerfile: Dockerfile
#     ports:
#       - 5000:5000
#     container_name: express-container
#     networks:
#       - mern-stack-network
#     volumes:
#       - ./api:/app
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     container_name: mongo-container
#     networks:
#       - mern-stack-network
#     volumes:
#       - mongoData:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=ridaali
#       - MONGO_INITDB_ROOT_PASSWORD=ridaali
#       - MONGO_INITDB_DATABASE=blog
# networks:
#   mern-stack-network:
# volumes:
#   mongoData:



